In [112]:
import pandas as pd
import numpy as np
from datetime import datetime

In [113]:
def extract_data(path):
    df = pd.read_csv(path)
    return df 
df_doctors = extract_data("../Data/Raw/doctors.csv")

In [114]:
def transform_doctors(df):

    # data type treatment
    df["specialization"] = df["specialization"].apply(lambda x: str(x))
    df["phone_number"] = df["phone_number"].apply(lambda x: str(x))
    df["hospital_branch"] = df["hospital_branch"].apply(lambda x: str(x))
    df["email"] = df["email"].apply(lambda x: str(x))
    
    #columns treatment
    df = df.rename(columns={"doctor_id": "IDdoctor"})
    df["IDdoctor"] = range(1, len(df) + 1) 
    df["name"] = df["first_name"] + " " + df["last_name"]
    df = df.drop(columns=["first_name", "last_name"])
    cols = list(df.columns)
    cols.remove("name")
    cols.insert(1, "name")
    df = df[cols]

    #creating columns

    df["salary"] = np.random.normal(loc=15000, scale=3000, size=10)
    df["salary"] = np.round(df["salary"], 2)

    df["increase"] = np.where((df["years_experience"] > 20),
                   df["salary"] * 0.4,
                   np.where((df["years_experience"] > 10),
                   df["salary"] * 0.1,
                   df["salary"] * 0))
    
    return df

In [115]:
df_doctors = transform_doctors(df_doctors)

In [116]:
df_doctors

,IDdoctor,name,specialization,phone_number,years_experience,hospital_branch,email,salary,increase
0,1,David Taylor,Dermatology,8322010158,17,Westside Clinic,dr.david.taylor@hospital.com,12212.04,1221.204
1,2,Jane Davis,Pediatrics,9004382050,24,Eastside Clinic,dr.jane.davis@hospital.com,14957.09,5982.836
2,3,Jane Smith,Pediatrics,8737740598,19,Eastside Clinic,dr.jane.smith@hospital.com,10187.53,1018.753
3,4,David Jones,Pediatrics,6594221991,28,Central Hospital,dr.david.jones@hospital.com,12411.09,4964.436
4,5,Sarah Taylor,Dermatology,9118538547,26,Central Hospital,dr.sarah.taylor@hospital.com,13512.39,5404.956
5,6,Alex Davis,Pediatrics,6570137231,23,Central Hospital,dr.alex.davis@hospital.com,13744.83,5497.932
6,7,Robert Davis,Oncology,8217493115,26,Westside Clinic,dr.robert.davis@hospital.com,11219.75,4487.900
7,8,Linda Brown,Dermatology,9069162601,5,Westside Clinic,dr.linda.brown@hospital.com,13571.74,0.000
8,9,Sarah Smith,Pediatrics,7387087517,26,Central Hospital,dr.sarah.smith@hospital.com,16651.84,6660.736
9,10,Linda Wilson,Oncology,6176383634,21,Eastside Clinic,dr.linda.wilson@hospital.com,12360.27,4944.108

In [94]:
df_patients = extract_data("../Data/Raw/patients.csv")

In [111]:
df_patients.head(15)

,IDpatient,name,gender,date_of_birth,contact_number,address,registration_date,insurance_provider,insurance_number,email,age
0,1,David Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,WellnessCorp,INS840674,david.williams@mail.com,70
1,2,Emily Smith,F,1984-10-12,8228188767,321 Maple Dr,2022-01-15,PulseSecure,INS354079,emily.smith@mail.com,41
2,3,Laura Jones,M,1977-08-21,8397029847,321 Maple Dr,2022-02-07,PulseSecure,INS650929,laura.jones@mail.com,48
3,4,Michael Johnson,F,1981-02-20,9019443432,123 Elm St,2021-03-02,HealthIndia,INS789944,michael.johnson@mail.com,45
4,5,David Wilson,M,1960-06-23,7734463155,123 Elm St,2021-09-29,MedCare Plus,INS788105,david.wilson@mail.com,65
5,6,Linda Jones,M,1963-06-16,7561777264,321 Maple Dr,2022-10-02,HealthIndia,INS613758,linda.jones@mail.com,62
6,7,Alex Johnson,F,1989-06-08,6278710077,789 Pine Rd,2021-12-25,MedCare Plus,INS465890,alex.johnson@mail.com,36
7,8,David Davis,F,1976-07-05,7090558393,456 Oak Ave,2021-05-25,WellnessCorp,INS545101,david.davis@mail.com,49
8,9,Laura Davis,M,1971-12-11,7060324619,321 Maple Dr,2022-09-18,PulseSecure,INS136631,laura.davis@mail.com,54
9,10,Michael Taylor,M,2001-10-13,7081396733,123 Elm St,2022-08-24,WellnessCorp,INS866577,michael.taylor@mail.com,24
10,11,Emily Jones,F,1966-12-04,8990604070,789 Pine Rd,2022-09-27,MedCare Plus,INS172991,emily.jones@mail.com,59
11,12,Laura Davis,F,1991-12-08,8135666049,321 Maple Dr,2023-04-27,MedCare Plus,INS104014,laura.davis@mail.com,34
12,13,Laura Johnson,F,1990-03-28,9059178882,321 Maple Dr,2021-12-23,WellnessCorp,INS373237,laura.johnson@mail.com,35
13,14,Alex Taylor,M,1968-02-27,7292262512,789 Pine Rd,2023-12-12,MedCare Plus,INS118070,alex.taylor@mail.com,58
14,15,Sarah Johnson,M,1964-05-11,6636028516,321 Maple Dr,2021-09-25,WellnessCorp,INS922209,sarah.johnson@mail.com,61

In [108]:
def transform_patients(df):

    # data type treatment
    df["gender"] = df["gender"].apply(lambda x: str(x))
    df["contact_number"] = df["contact_number"].apply(lambda x: str(x))
    df["address"] = df["address"].apply(lambda x: str(x))
    df["insurance_provider"] = df["insurance_provider"].apply(lambda x: str(x))
    df["insurance_number"] = df["insurance_number"].apply(lambda x: str(x))
    df["email"] = df["email"].apply(lambda x: str(x))

    df["date_of_birth"] = pd.to_datetime(df["date_of_birth"], format="%Y-%m-%d")
    df["registration_date"] = pd.to_datetime(df["registration_date"], format="%Y-%m-%d")

    #columns treatment
    df = df.rename(columns={"patient_id": "IDpatient"})
    df["IDpatient"] = range(1, len(df) + 1) 

    df["name"] = df["first_name"] + " " + df["last_name"]
    df = df.drop(columns=["first_name", "last_name"])

    cols = list(df.columns)
    cols.remove("name")
    cols.insert(1, "name")

    df = df[cols]

    #creating columns

    now = datetime.today()

    df["age"] = df["date_of_birth"].apply(
    lambda x: now.year - x.year - ((now.month, now.day) < (x.month, x.day)))

    return df

In [109]:
df_patients = transform_patients(df_patients)

In [110]:
df_patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   IDpatient           50 non-null     int64
 1   name                50 non-null     object
 2   gender              50 non-null     object
 3   date_of_birth       50 non-null     datetime64[ns]
 4   contact_number      50 non-null     object
 5   address             50 non-null     object
 6   registration_date   50 non-null     datetime64[ns]
 7   insurance_provider  50 non-null     object
 8   insurance_number    50 non-null     object
 9   email               50 non-null     object
 10  age                 50 non-null     int64
dtypes: datetime64[ns](2), int64(2), object(7)
memory usage: 4.4+ KB

In [13]:
df_treatments = extract_data("../Data/Raw/treatments.csv")

In [14]:
df_treatments.head()

,treatment_id,appointment_id,treatment_type,description,cost,treatment_date
0,T001,A001,Chemotherapy,Basic screening,3941.97,2023-08-09
1,T002,A002,MRI,Advanced protocol,4158.44,2023-06-09
2,T003,A003,MRI,Standard procedure,3731.55,2023-06-28
3,T004,A004,MRI,Basic screening,4799.86,2023-09-01
4,T005,A005,ECG,Standard procedure,582.05,2023-07-06

In [15]:
def transform_treatments(df):

    # data type treatment
    df["treatment_type"] = df["treatment_type"].apply(lambda x: str(x))
    df["description"] = df["description"].apply(lambda x: str(x))
    
    df["treatment_date"] = pd.to_datetime(df["treatment_date"], format="%Y-%m-%d")

     #columns treatment
    df = df.rename(columns={"treatment_id": "IDtreatment"})
    df["IDtreatment"] = range(1, len(df) + 1)
    df = df.rename(columns={"appointment_id": "IDappointment"})
    df["IDappointment"] = range(1, len(df) + 1) 

    return df

In [16]:
df_treatments = transform_treatments(df_treatments)

In [17]:
df_treatments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   IDtreatment     200 non-null    int64
 1   IDappointment   200 non-null    int64
 2   treatment_type  200 non-null    object
 3   description     200 non-null    object
 4   cost            200 non-null    float64
 5   treatment_date  200 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 9.5+ KB

In [18]:
df_appointments = extract_data("../Data/Raw/appointments.csv")

In [19]:
df_appointments.head()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,reason_for_visit,status
0,A001,P034,D009,2023-08-09,15:15:00,Therapy,Scheduled
1,A002,P032,D004,2023-06-09,14:30:00,Therapy,No-show
2,A003,P048,D004,2023-06-28,8:00:00,Consultation,Cancelled
3,A004,P025,D006,2023-09-01,9:15:00,Consultation,Cancelled
4,A005,P040,D003,2023-07-06,12:45:00,Emergency,No-show

In [20]:
def transform_appointments(df):

    # data type treatment
    df["reason_for_visit"] = df["reason_for_visit"].apply(lambda x: str(x))
    df["status"] = df["status"].apply(lambda x: str(x))
    
    df["appointment_date"] = pd.to_datetime(df["appointment_date"], format="%Y-%m-%d")
    df["appointment_time"] = pd.to_datetime(df["appointment_time"], format="%H:%M:%S").dt.time

    #columns treatment

    df = df.rename(columns={"appointment_id": "IDappointment"})
    df["IDappointment"] = range(1, len(df) + 1)

    df["patient_id"] = df["patient_id"].str[1:]
    df["patient_id"] = pd.to_numeric(df["patient_id"], errors="coerce").astype(int)
    df = df.rename(columns={"patient_id": "IDpatient"})
    
    df["doctor_id"] = df["doctor_id"].str[1:]
    df["doctor_id"] = pd.to_numeric(df["doctor_id"], errors="coerce").astype(int)
    df = df.rename(columns={"doctor_id": "IDdoctor"})

    return df

In [21]:
df_appointments = transform_appointments(df_appointments)

In [22]:
df_appointments.head(10)

,IDappointment,IDpatient,IDdoctor,appointment_date,appointment_time,reason_for_visit,status
0,1,34,9,2023-08-09,15:15:00,Therapy,Scheduled
1,2,32,4,2023-06-09,14:30:00,Therapy,No-show
2,3,48,4,2023-06-28,08:00:00,Consultation,Cancelled
3,4,25,6,2023-09-01,09:15:00,Consultation,Cancelled
4,5,40,3,2023-07-06,12:45:00,Emergency,No-show
5,6,45,6,2023-06-19,16:15:00,Checkup,Scheduled
6,7,1,7,2023-04-09,10:30:00,Consultation,Scheduled
7,8,16,10,2023-05-24,08:45:00,Consultation,Cancelled
8,9,39,10,2023-03-05,13:45:00,Follow-up,Scheduled
9,10,5,3,2023-01-13,15:30:00,Therapy,Completed

In [23]:
df_billing = extract_data("../Data/Raw/billing.csv")

In [24]:
df_billing.head()

,bill_id,patient_id,treatment_id,bill_date,amount,payment_method,payment_status
0,B001,P034,T001,2023-08-09,3941.97,Insurance,Pending
1,B002,P032,T002,2023-06-09,4158.44,Insurance,Paid
2,B003,P048,T003,2023-06-28,3731.55,Insurance,Paid
3,B004,P025,T004,2023-09-01,4799.86,Insurance,Failed
4,B005,P040,T005,2023-07-06,582.05,Credit Card,Pending

In [25]:
def transform_billing(df):

    # data type treatment
    df["payment_status"] = df["payment_status"].apply(lambda x: str(x))
    df["payment_method"] = df["payment_method"].apply(lambda x: str(x))
    
    df["bill_date"] = pd.to_datetime(df["bill_date"], format="%Y-%m-%d")

    #columns treatment

    df = df.rename(columns={"bill_id": "IDbill"})
    df["IDbill"] = range(1, len(df) + 1)

    df["patient_id"] = df["patient_id"].str[1:]
    df["patient_id"] = pd.to_numeric(df["patient_id"], errors="coerce").astype(int)
    df = df.rename(columns={"patient_id": "IDpatient"})
    df["treatment_id"] = df["treatment_id"].str[1:]
    df["treatment_id"] = pd.to_numeric(df["treatment_id"], errors="coerce").astype(int)
    df = df.rename(columns={"treatment_id": "IDtreatment"})

    

    

    return df

In [26]:
df_billing = transform_billing(df_billing)

In [27]:
df_billing.head()

,IDbill,IDpatient,IDtreatment,bill_date,amount,payment_method,payment_status
0,1,34,1,2023-08-09,3941.97,Insurance,Pending
1,2,32,2,2023-06-09,4158.44,Insurance,Paid
2,3,48,3,2023-06-28,3731.55,Insurance,Paid
3,4,25,4,2023-09-01,4799.86,Insurance,Failed
4,5,40,5,2023-07-06,582.05,Credit Card,Pending